### PR TITLE
fix(dashboard): tenant selector

### LINKED ISSUE #2076: Tenant selection not displaying full list
It is not possible to select a tenant other than default.

Internal message reference:
https://littlehorseworkspace.slack.com/archives/C060A2XCX9D/p1770926664497299

### PR DESCRIPTION
**Pull request by bryson-g**
resolves #2076

### CODE REVIEW

File: dashboard/src/app/getWhoami.ts [hunk 1]
```diff
@@ -8,29 +7,14 @@ const getWhoAmI = async (): Promise<WhoAmI> => {
   const session = await getServerSession(authOptions)
   const client = lhConfig.getClient(session?.accessToken)
 
-  const { id, perTenantAcls, globalAcls } = await client.whoami({})
-
-  const tenants = getTenants({ perTenantAcls, globalAcls })
+  const { id } = await client.whoami({})
+  const { results } = await client.searchTenant({})
```
Comment (coltmcnealy-lh) [inline dashboard/src/app/getWhoami.ts]: We need to merge the results of `client.searchTenant()` with the results of `client.whoami()`. In many cases, the user won't have permission to search tenants and will get `PERMISSION_DENIED` (for example, in a multi-tenant environment).

File: dashboard/src/app/getWhoami.ts [hunk 2]
```diff
@@ -7,14 +8,39 @@ const getWhoAmI = async (): Promise<WhoAmI> => {
...
 
+const getTenants = ({ perTenantAcls, globalAcls }: Pick<Principal, 'globalAcls' | 'perTenantAcls'>): string[] => {
+  let tenants: string[] = []
+  if (globalAcls && hasDefaultAccess(globalAcls)) {
+    tenants = ['default']
+  }
+  return [...tenants, ...Object.keys(perTenantAcls)]
+}
+
+const hasDefaultAccess = ({ acls }: ServerACLs): boolean => {
```
Comment (coltmcnealy-lh) [inline dashboard/src/app/getWhoami.ts]: Suggest that this is not `hasDefaultAccess` but rather `hasGlobalAccess`

File: dashboard/src/app/getWhoami.ts [hunk 3]
```diff
@@ -7,14 +8,39 @@ const getWhoAmI = async (): Promise<WhoAmI> => {
...
+  return acls.some(
+    ({ resources, allowedActions }) =>
+      resources.includes(ACLResource.ACL_ALL_RESOURCES) && allowedActions.includes(ACLAction.ALL_ACTIONS)
```
Comment (coltmcnealy-lh) [inline dashboard/src/app/getWhoami.ts]: Recommend `resources.includes(ACLResource.ACL_TENANT)`

File: dashboard/src/app/getWhoami.ts [hunk 4]
```diff
@@ -7,14 +8,39 @@ const getWhoAmI = async (): Promise<WhoAmI> => {
...
   return {
     user: session?.user || { name: id?.id },
     tenants,
   }
 }
 
+const getTenants = ({ perTenantAcls, globalAcls }: Pick<Principal, 'globalAcls' | 'perTenantAcls'>): string[] => {
+  let tenants: string[] = []
+  if (globalAcls && hasDefaultAccess(globalAcls)) {
+    tenants = ['default']
```
Comment (coltmcnealy-lh) [inline dashboard/src/app/getWhoami.ts]: This isn't needed anymore, as the LH Server will return the `default` tenant now in `rpc SearchTenant()`.

File: dashboard/src/app/getWhoami.ts (hunk 3 above)
Comment (bryson-g) [reply dashboard/src/app/getWhoami.ts]:
```
const hasGlobalAccess = ({ acls }: ServerACLs): boolean => {
  return acls.some(
    ({ resources, allowedActions }) =>
      resources.includes(ACLResource.ACL_TENANT) && allowedActions.includes(ACLAction.ALL_ACTIONS)
  )
}
```

So this?
