### PR TITLE
Idempotency on PutWfSpec

### LINKED ISSUE #544: Idempotency on PutWfSpec
### Context

In order to reduce duplication in the WfSpec versions, it is proposed to implement idempotence in the PutWfSpec service.

### Proposal

Add a new field to `PutWfSpecRequest` proto message, which allows you to define what type of update you want to execute.

Allow all changes:

1. Doesn't exist: just create it
2. Exists, and is the same:
a. Don't change anything
b. Return OK
3. Exists, and is different:
a. Create a new WfSpec with a different version (either major or revision)
b Return OK

Allow only minor revision:

1. Doesn't exist: just create it
2. Exists, and is the same:
a. Don't change anything
b. Return OK
3. Exists, and is different and change the revision:
a. Create a new WfSpec with a different version
b. Return OK
4. Exists, and is different and change the majorVersion:
a. Fail with the FAILED_PRECONDITION response code.

Reject changes:

1. Doesn't exist: just create it
2. Exists, and is the same:
a. Don't change anything
b. Return OK
3. Exists, and is different:
a. Fail with the ALREADY_EXISTS response code.

### Scope

This issue is scoped to the procedure PutWfSpec. Out of scope saving the policy in the storage.

### Component

* [x] LH Server
* [x] Python SDK
* [x] Go SDK
* [x] Java SDK
* [x] C# SDK

### Links

- https://grpc.github.io/grpc/core/md_doc_statuscodes.html

### PR DESCRIPTION
**Pull request by mijailr**
Introduces three update types to PutWFSpec:
- `ALL`
- `MINOR_REVISION_ONLY`
- `NONE`

## Allow all changes: (`ALL`)

- Doesn't exist: just create it
- Exists, and is the same:
  1. Don't change anything
  2. Return OK
- Exists, and is different:
  1. Create a new WfSpec with a different version (either major or revision)
  2. Return OK

## Allow only minor revision: (`MINOR_REVISION_ONLY`)

- Doesn't exist: just create it
- Exists, and is the same:
  1. Don't change anything
  2. Return OK
- Exists, and is different and change the revision:
  1. Create a new WfSpec with a different version
  2. Return OK
- Exists, and is different and change the majorVersion:
  1. Fail with the `FAILED_PRECONDITION` response code.

## Reject changes: (`NONE`)

- Doesn't exist: just create it
- Exists, and is the same:
  1. Don't change anything
  2. Return OK
- Exists, and is different:
  1. Fail with the `ALREADY_EXISTS` response code.

Resolves #544

### CODE REVIEW

File: examples/external-event/src/main/java/io/littlehorse/examples/ExternalEventExample.java [hunk 1]
```diff
@@ -35,14 +35,14 @@ public static Workflow getWorkflow() {
         return new WorkflowImpl(
             "example-external-event",
             wf -> {
-                WfRunVariable name = wf.addVariable("name", VariableType.STR).searchable();
+                WfRunVariable name = wf.addVariable("person", VariableType.STR).searchable();
```
Comment (eduwercamacaro) [inline examples/external-event/src/main/java/io/littlehorse/examples/ExternalEventExample.java:38]: Probably we don't want this

File: schemas/service.proto [hunk 2]
```diff
@@ -33,6 +33,13 @@ message PutWfSpecRequest {
   string entrypoint_thread_name = 6;
   optional WorkflowRetentionPolicy retention_policy = 8;
   reserved 9;
+  optional AllowedUpdateType allowed_updates = 10;
+}
+
+enum AllowedUpdateType {
+  ALL = 0;
```
Comment (eduwercamacaro) [inline schemas/service.proto:40]: Comments will be useful. And I believe this will add javadoc for the generated Java enum.

File: sdk-go/examples/basic/README.md [hunk 3]
```diff
@@ -1,4 +1,4 @@
-# Basic Example
+ # Basic Example
```
Comment (eduwercamacaro) [inline sdk-go/examples/basic/README.md:1]: is this expected?

File: sdk-python/tests/test_workflow.py [hunk 4]
```diff
@@ -814,6 +814,7 @@ def my_entrypoint(thread: WorkflowThread) -> None:
         self.assertEqual(
             wf.compile(),
             PutWfSpecRequest(
+                allowed_updates="ALL",
```
Comment (eduwercamacaro) [inline sdk-python/tests/test_workflow.py:817]: Is not clear if we are covering the case when this function is invoked without the allowed_updates argument

File: server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java [hunk 5]
```diff
@@ -61,6 +66,7 @@ public void initFrom(Message proto, ExecutionContext context) {
         PutWfSpecRequest p = (PutWfSpecRequest) proto;
         name = p.getName();
         entrypointThreadName = p.getEntrypointThreadName();
+        allowedUpdateType = p.hasAllowedUpdates() ? p.getAllowedUpdates() : AllowedUpdateType.ALL;
```
Comment (eduwercamacaro) [inline server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java:69]: suggestion:
what if we add a private constant for AllowedUpdateType.ALL?

maybe smth like this:

private static AllowedUpdateType defaultUpdateType = ...

File: examples/external-event/src/main/java/io/littlehorse/examples/ExternalEventExample.java (hunk 1 above)
Comment (mijailr) [reply examples/external-event/src/main/java/io/littlehorse/examples/ExternalEventExample.java]: I reverted this file back to original

File: server/src/main/java/io/littlehorse/common/util/WfSpecUtil.java [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+import io.littlehorse.common.model.getable.global.wfspec.WfSpecModel;
+import io.littlehorse.common.model.getable.global.wfspec.thread.ThreadVarDefModel;
+import io.littlehorse.sdk.common.proto.WfSpec;
+import io.littlehorse.sdk.common.proto.WfSpecId;
+import java.util.Arrays;
+import java.util.Date;
+import java.util.Map;
+import java.util.Set;
+
+public class WfSpecUtil {
```
Comment (eduwercamacaro) [inline server/src/main/java/io/littlehorse/common/util/WfSpecUtil.java:13]: suggestion:

add a private constructor for this class to prevent class instances since it only contains static methods

**Review by eduwercamacaro — APPROVED** [review]
Good job. just a few suggestions :)

File: sdk-python/tests/test_workflow.py (hunk 4 above)
Comment (mijailr) [reply sdk-python/tests/test_workflow.py:817]: I'll delegate this to @sauljabin

Comment (coltmcnealy-lh) [reply sdk-python/tests/test_workflow.py:817]: The way protobuf works is that it's not an `optional` field, so if you don't set it, then it is treated as the protobuf "zero" field. That means the enum value `0`; in this case, allowing `ALL` udpates.

File: sdk-go/examples/basic/workflow.go [hunk 7]
```diff
@@ -14,7 +14,7 @@ func Greet(name string) string {
 }
 
 func MyWorkflow(wf *wflib.WorkflowThread) {
-	nameVar := wf.AddVariableWithDefault("name", model.VariableType_STR, "Qui-Gon Jinn")
```
Comment (coltmcnealy-lh) [inline sdk-go/examples/basic/workflow.go:17]: This will break the readme for the example, please revert this change.

File: schemas/service.proto [hunk 8]
```diff
@@ -33,6 +33,17 @@ message PutWfSpecRequest {
...
   optional WorkflowRetentionPolicy retention_policy = 8;
   reserved 9;
+  optional AllowedUpdateType allowed_updates = 10;
+}
+
+// Defines the allowed update type
+// ALL - Creates either a revision or majorVersion when WfSpec changes
+// MINOR_REVISION_ONLY - Allow revision updates but reject majorVersion
+// NONE - Reject any update
+enum AllowedUpdateType {
```
Comment (coltmcnealy-lh) [inline schemas/service.proto:43]: One quirk with protobuf is that we won't be able to have any other enum value in our entire package that is called `ALL`, `MINOR_REVISION_ONLY`, or `NONE`.

I definitely don't think we should reserve `ALL` or `NONE` for this use case. Can we please put a prefix? Or make it `ALL_UPDATES`, `MINOR_REVISION_UPDATES`, and `NO_UPDATES`?

File: sdk-python/tests/test_workflow.py [hunk 9]
```diff
@@ -1160,6 +1166,7 @@ def my_entrypoint(thread: WorkflowThread) -> None:
...
```
Comment (coltmcnealy-lh) [inline sdk-python/tests/test_workflow.py:1169]: As per the comment above, if you don't set this field, it defaults to `ALL`, so there's not really any need to set it.

File: schemas/service.proto [hunk 10]
```diff
@@ -33,6 +33,17 @@ message PutWfSpecRequest {
   string entrypoint_thread_name = 6;
   optional WorkflowRetentionPolicy retention_policy = 8;
   reserved 9;
+  optional AllowedUpdateType allowed_updates = 10;
```
Comment (coltmcnealy-lh) [inline schemas/service.proto:36]: Please make this not an optional field. It will default to the enum value zero. That is backwards compatible.

File: server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java [hunk 11]
```diff
@@ -30,6 +32,9 @@ public class PutWfSpecRequestModel extends MetadataSubCommand<PutWfSpecRequest>
     public Map<String, ThreadSpecModel> threadSpecs;
     public String entrypointThreadName;
     public WorkflowRetentionPolicyModel retentionPolicy;
+    public AllowedUpdateType allowedUpdateType;
+
+    private static AllowedUpdateType defaultUpdateType = AllowedUpdateType.ALL;
```
Comment (coltmcnealy-lh) [inline server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java:37]: This shouldn't be necessary.

File: server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java [hunk 12]
```diff
@@ -97,10 +105,32 @@ public WfSpec process(MetadataCommandExecution executionContext) {
...
+            return optWfSpec.get().toProto().build();
+        }
+
+        verifyUpdateType(allowedUpdateType, spec, optWfSpec);
         metadataManager.put(spec);
         return spec.toProto().build();
     }
 
+    private void verifyUpdateType(AllowedUpdateType updateType, WfSpecModel spec, Optional<WfSpecModel> oldSpec) {
+        switch (updateType) {
```
Comment (coltmcnealy-lh) [inline server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java:118]: I'd like to have a checkstyle rule which throws an error if any enum types are missing from a switch. Could we please address that here?

**Review by coltmcnealy-lh — CHANGES_REQUESTED** [review]
Several small changes requested, mostly around how proto works.

File: schemas/service.proto (hunk 8 above)
Comment (mijailr) [reply schemas/service.proto:43]: Oh understood, will do.

File: server/src/main/java/io/littlehorse/common/util/WfSpecUtil.java [hunk 13]
```diff
@@ -0,0 +1,57 @@
...
+     * @param right WfSpecModel compared against
+     * @return true when it is equal, false otherwise.
+     */
+    public static boolean equals(WfSpecModel left, WfSpecModel right) {
+        WfSpec.Builder copy = left.toProto();
+        Timestamp date = LHUtil.fromDate(new Date());
+        sanitize(copy, date);
+        WfSpec.Builder toCopy = right.toProto();
+        sanitize(toCopy, date);
+        return Arrays.equals(copy.build().toByteArray(), toCopy.build().toByteArray());
```
Comment (coltmcnealy-lh) [inline server/src/main/java/io/littlehorse/common/util/WfSpecUtil.java:29]: This is actually a lot nicer than I thought it would come out to be. Good work!

File: server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java (hunk 12 above)
Comment (mijailr) [reply server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java:118]: You mean this?

image

Comment (coltmcnealy-lh) [reply server/src/main/java/io/littlehorse/common/model/metadatacommand/subcommand/PutWfSpecRequestModel.java:118]: Yes, that. Thanks!

**Review by coltmcnealy-lh — APPROVED** [review]
Going to pre-emptively approve this, please merge once you've addressed the prior feedback.
